version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
